Poseidon MWE
yatima-inc/Poseidon.lean pull request #6
Opened 2022-10-06 01:14 UTC by mpenciak

This PR implements a basic version of the Poseidon hash function.

As of now the hash implementation passes the `poseidonperm_x5_255_5 ` test in the [reference implementation](https://extgit.iaik.tugraz.at/krypto/hadeshash). 

TODO List before merging:

- [x] Add the Lurk `Poseidon.Profile`
- [ ] Write Poseidon hash tests for Lurk profile
- [x] Move the MDS and Round Constants to a separate "Constants"
- [ ] Documentation
- [x] Add license

2022-10-19 11:41 UTC, DanielRrr commented on Poseidon/ForYatimaStdLib.lean
> +  ans.set! (ans.size - 1) (ans[(ans.size - 1)]! + b.toUInt8)
All those definitions are in the standard library now, so consider bumping `YatimaStdLib`

2022-10-19 11:41 UTC, DanielRrr commented on Poseidon/Tests/MDS.lean
> +
Is it in progress now?

2022-10-20 15:12 UTC, mpenciak commented
This PR also closes #9.

What's missing is documentation and LSpec tests, I'll make separate PRs for that so we're not holding up its use in `Lurk.lean`

2022-10-20 15:18 UTC, arthurpaulino requested changes

2022-10-20 15:20 UTC, arthurpaulino commented on Poseidon/Tests/Hash.lean
> +  test "poseidonperm_x5_255_5" (Poseidon.hashInput testProfile testContext input == output)
That would allow you to call `lake exe lspec` to run the test suite

2022-10-20 15:20 UTC, mpenciak commented on Poseidon/Tests/Hash.lean
> +  test "poseidonperm_x5_255_5" (Poseidon.hashInput testProfile testContext input == output)
Yeah the main testing suite is going to be setup that way with a github CI integration, the test was just in there for personal use while I was developing to make sure I got everything right.

2022-10-20 15:21 UTC, arthurpaulino commented on Poseidon/Tests/Hash.lean
> +  test "poseidonperm_x5_255_5" (Poseidon.hashInput testProfile testContext input == output)
Ah so it's a WIP

2022-10-20 15:21 UTC, arthurpaulino approved these changes

2022-10-20 15:28 UTC, merged